#!/usr/bin/env perl
$latex = 'platex %O %S';
$bibtex = 'pbibtex %O %B';
$dvipdf = 'dvipdfmx %O -o %D %S';
$pdf_mode = 3; # generates pdf via dvipdfmx
$pdf_update_method = 2;
$max_repeat       = 5;
$biber = 'biber --bblencoding=utf8 -u -U --output_safechars';

